os: linux
dist: xenial

cache:
  yarn: true
  directories:
    - node_modules

language: node_js

# always test things that aren't pushes (like PRs)
# never test tags or pushes to non-master branches (wait for PR)
if: type != push OR (tag IS blank AND branch = master)

install:
  - yarn config set ignore-engines true
  - yarn install

before_script:
  - export NODE_OPTIONS=--max_old_space_size=4096

jobs:
  include:
    - stage: validate
      name: Lint Commits
      script:
        - yarn add -W @commitlint/travis-cli
        - commitlint-travis
    - name: Lint Files
      script: yarn lint:ci
    - stage: test
      name: Unit Test
      script:
        - yarn build
        - yarn test
