sudo: false

language: node_js

# always test things that aren't pushes (like PRs)
# never test tags or pushes to non-master branches (wait for PR)
if: type != push OR (tag IS blank AND branch = master)

install:
  - npm install


before_script:
  - export NODE_OPTIONS=--max_old_space_size=4096

jobs:
  include:
    - stage: validate
      name: Lint Commits
      script:
        - npm install @commitlint/travis-cli
        - commitlint-travis
    - name: Lint Files
      script: npm run lint
    - stage: test
      name: Unit Test
      script:
        - npm run bootstrap
        - npm test
