sudo: false

language: node_js

install:
  - npm install

jobs:
  include:
    - stage: validate
      name: Lint Commits
      script:
        - npm install @commitlint/travis-cli
        - commitlint-travis
    - name: Lint Files
      script: npm run lint:no-fail
    - name: Danger
      script:
        - npm install danger
        - ./node_modules/.bin/danger ci
    - stage: test
      name: Unit Test
      script:
        - npm run bootstrap
        - npm test
