sudo: false

language: node_js

cache: npm

install:
  - npm install
  - npm run bootstrap

jobs:
  include:
    - stage: test
      name: Lint
      script: npm run lint:no-fail
    - name: Unit Test
      script: npm test
    - name: Danger
      script: npm run danger -- ci
